# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    match(
      type: "appstore",
      git_url: "git@gitlab.com:lewis-king/FootballTriviaCerts.git"
    ) # more information: https://codesigning.guide   
    gym(scheme: "FootballTrivia") # Build your app - more options available
    pilot
  end
  desc "Deploy a new version to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "./AwesomeProject.xcodeproj") # Increment build No.
    match(
      type: "appstore",
      git_url: "git@gitlab.com:lewis-king/FootballTriviaCerts.git"
    )
    # snapshot
    gym(scheme: "FootballTrivia") # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end
